source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.2"
gem "pg", "~> 1.5"
gem "redis", "~> 5.0"
gem "puma", "~> 6.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug"
  gem "rspec-rails"
end
